baseURL = "/"
languageCode = "en-US"
defaultContentLanguage = "en"

title = "ktls.io"
theme = "learn"
# themesdir = "../.."
metaDataFormat = "yaml"
defaultContentLanguageInSubdir= true

[params]
  editURL = "https://github.com/klts-io/website/edit/master/content/"
  description = "Website for KLTS"
  author = "Shiming Zhang"
  showVisitedLinks = true
  disableBreadcrumb = false
  disableNextPrev = false
  disableLandingPageButton = true
  disableMermaid = false
  customMermaidURL = "https://unpkg.com/mermaid@8.8.0/dist/mermaid.min.js"
  titleSeparator = ":"

[outputs]
home = [ "HTML", "RSS", "JSON"]

[Languages]
[Languages.en]
name = "KLTS"
weight = 1
languageName = "English"
landingPageURL = "/en"
landingPageName = "<i class='fas fa-home'></i> Home"

[[Languages.en.menu.shortcuts]]
name = "<i class='fab fa-fw fa-github'></i> Kubepatch repo"
identifier = "ds"
url = "https://github.com/klts-io/kubepatch"
weight = 10

[[Languages.en.menu.shortcuts]]
name = "<i class='fas fa-fw fa-bullhorn'></i> Credits"
url = "contributors"
weight = 30

[Languages.zh]
name = "KLTS"
weight = 3
languageName = "简体中文"
landingPageURL = "/zh"
landingPageName = "<i class='fas fa-home'></i> 主页"

[[Languages.zh.menu.shortcuts]]
name = "<i class='fab fa-fw fa-github'></i> Kubepatch 仓库"
identifier = "ds"
url = "https://github.com/klts-io/kubepatch"
weight = 10

[[Languages.zh.menu.shortcuts]]
name = "<i class='fas fa-fw fa-bullhorn'></i> 鸣谢"
url = "contributors"
weight = 30
